export const Views = Object.freeze({
  Splash: 'splash',
  PresentSelect: 'present-select',
  OpenPresent: 'open-present',
  FinalRound: 'final-round',
  Summary: 'summary',
});

export const ImageKeys = Object.freeze({
  Amazon: 'Amazon',
  BanvilleAndJones: 'Banville and Jones',
  BestBuy: 'BestBuy',
  Amazon: 'Amazon',
  BlackMarketProvisions: 'Black Market Provisions',
  BostonPizza: 'Boston Pizza',
  Chapters: 'Chapters',
  CoalAndCanary: 'Coal and Canary',
  EBGames: 'EB Games',
  GolfTown: 'Golf Town',
  GoodLocal: 'The Good Local',
  HomeDepot: 'Home Depot',
  Ikea: 'IKEA',
  Indigo: 'Indigo',
  KHAB: 'KHAB',
  LuxeBBQ: 'Luxe BBQ',
  Marshalls: 'HomeSense',
  MastermindToys: 'Mastermind Toys',
  Mcdonalds: 'Mcdonalds',
  McNally: 'McNally Robinson',
  Michaels: 'Michael\'s',
  Netflix: 'Netflix',
  Nintendo: 'Nintendo eShop',
  OhDoughnuts: 'Oh Doughnuts',
  Playstation: 'Playstation',
  SkipTheDishes: 'SkipTheDishes',
  SportChek: 'Sport Chek',
  Starbucks: 'Starbucks',
  Steam: 'Steam',
  Superstore: 'Superstore',
  TimHortons: 'Tim Hortons',
  UberEats: 'UberEats',
  Walmart: 'Walmart',
});
